# Generated by Django 6.0.1 on 2026-02-06 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0003_rename_subcategory_subcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
