# Generated by Django 6.0.1 on 2026-02-27 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0005_alter_subcategorymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator("^[A-Z][a-zA-Z\\s\\'-]{1,29}$", 'The name must begin with a capital letter, a space, a hyphen, or an apostrophe')]),
        ),
    ]
