# Generated by Django 6.0.1 on 2026-02-16 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator("^[A-ZА-ЯІЇЄҐ][a-zA-Zа-яіїєґА-ЯІЇЄҐ\\s\\',-]*$", 'Only alpha characters, space, apostrophe, comma, hyphen are allowed')]),
        ),
    ]
