# Generated by Django 6.0.1 on 2026-02-27 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator("^[A-Z][a-zA-Z\\s\\'-]{1,29}$", 'The name must begin with a capital letter, a space, a hyphen, or an apostrophe')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator("^[A-Z][a-zA-Z\\s\\'-]{1,29}$", 'The name must begin with a capital letter, a space, a hyphen, or an apostrophe')]),
        ),
    ]
