# Generated by Django 6.0.1 on 2026-02-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('subcategory', '0002_subcategory_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='SubCategoryModel',
        ),
    ]
